# Generated by Django 2.1.3 on 2018-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('price', models.PositiveSmallIntegerField(verbose_name='가격')),
                ('defence', models.PositiveSmallIntegerField(verbose_name='방어점')),
            ],
        ),
        migrations.CreateModel(
            name='JobClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
            ],
        ),
    ]
